[package]
name = "sbalite"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
reqwest = { version = "0.12", default-features = false, features = ["stream", "json", "rustls-tls-webpki-roots"] }
mime_guess = "2"
toml = "0.8"
chrono = { version = "0.4", features = ["clock"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
futures-util = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
rust-embed = "8"
base64 = "0.22"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }